[build]
  functions = "netlify/functions"

[context.branch-deploy]
  environment = { CONTENTFUL_ENVIRONMENT = "development" }

[context.deploy-preview]
  [context.deploy-preview.environment]
    CONTENTFUL_ENVIRONMENT = "development"

[context.dev]
  [context.dev.environment]
    CONTENTFUL_ENVIRONMENT = "development"

[context.production]
  [context.production.environment]
    CONTENTFUL_ENVIRONMENT = "master"